global:
  storage: keyring
  keyring-backend: system
  google:
    authorize_endpoint: https://accounts.google.com/o/oauth2/auth
    devicecode_endpoint: https://oauth2.googleapis.com/device/code
    token_endpoint: https://accounts.google.com/o/oauth2/token
    redirect_uri: urn:ietf:wg:oauth:2.0:oob
    imap_endpoint: imap.gmail.com
    pop_endpoint: pop.gmail.com
    smtp_endpoint: smtp.gmail.com
    sasl_method: OAUTHBEARER
    scope: https://mail.google.com/
    client_id: <CLIENTID>
    client_secret: <CLIENTSECRET>
  o365:
    authorize_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    devicecode_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/devicecode
    token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
    redirect_uri: https://login.microsoftonline.com/common/oauth2/nativeclient
    tenant: common
    imap_endpoint: outlook.office365.com
    pop_endpoint: outlook.office365.com
    smtp_endpoint: smtp.office365.com
    sasl_method: XOAUTH2
    scope: "offline_access https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/POP.AccessAsUser.All https://outlook.office.com/SMTP.Send"
    client_id: 08162f7c-0fd2-4200-a84a-f25a4db0b584
    client_secret: "TxRBilcHdC6WGBee]fs?QR:SJ8nI[g82"
accounts:
  <email>@gmail.com:
    provider: google
    authflow: localhostauthcode
  <email>@outlook.com:
    provider: o365
    authflow: localhostauthcode
